### ISSUE TITLE
Broken links in the readme

### ISSUE THREAD

**Issue by dvingo** [clojure/tools.gitlibs#2]
The links listed in this section:
https://github.com/clojure/tools.gitlibs#developer-information
do not resolve to their intended locations (at least the API docs and how to contribute).

**Comment by puredanger** [comment]
Thanks, I'll update. The API docs are generated but for some reason github pages does not work on this repo and I've never figured out why, so the link is right there (content is at https://github.com/clojure/tools.gitlibs/blob/gh-pages/index.html) but it's something else.

**Comment by puredanger** [comment]
Fixed (removed API link for now, but API is doc'ed in readme)

**Comment by dvingo** [comment]
huh, strange - well, thanks for the quick reply!
